### ISSUE TITLE
KeyError with optional NestedDictSettings in NestedDictSettings

### ISSUE THREAD

**Issue by fenryxo** [pawamoy/django-appsettings#91]
Ubuntu 18.04, Python 3.6.

Settings declaration:

```py
class MySettings(AppSettings):
    api = NestedDictSetting(
        settings=dict(
            server=StringSetting(required=True),
            port=IntegerSetting(default=80),
            signature=NestedDictSetting(settings=dict(
                key_file=StringSetting(required=True, min_length=1),
                cert_file=StringSetting(required=True, min_length=1),
                signature_method=StringSetting(default='RSA_SHA512', min_length=1),
                digest_method=StringSetting(default='SHA512', min_length=1),
            ))
        ),
        required=True
    )
```

Django settings module:

```py
API = {
    "SERVER": "localhost"
}
```

`MySettings.check()` raises `KeyError`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".../venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File ".../venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File ".../venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File ".../venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File ".../venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File ".../venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".../venv/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/jjanousek/git/others/eidas-specific-node/eidas_node/connector/apps.py", line 15, in ready
    check_settings()
  File "/home/jjanousek/git/others/eidas-specific-node/eidas_node/connector/settings.py", line 126, in check_settings
    MySettings.check()
  File ".../venv/lib/python3.6/site-packages/appsettings/__init__.py", line 198, in check
    setting.check()
  File ".../venv/lib/python3.6/site-packages/appsettings/settings.py", line 1058, in check
    subsetting.check()
  File ".../venv/lib/python3.6/site-packages/appsettings/settings.py", line 1050, in check
    raw_value = self.raw_value
  File ".../venv/lib/python3.6/site-packages/appsettings/settings.py", line 136, in raw_value
    return self.parent_setting.raw_value[self.full_name]
KeyError: 'SIGNATURE'
```

Expected behavior:
* No `KeyError` raised.
* `MySettings().api["signature"]` is an empty dict.

**Comment by ziima** [comment]
This looks like a problem which prevents wrapping `NestedDictSetting` into `NestedListSetting`. Maybe the underlying cause will be the same.

**Comment by rastytheamateur** [comment]
Should be closed, shouldn't it?

**Comment by ziima** [comment]
Indeed.
